php:
    preset: laravel

    enabled:
        - align_double_arrow
        - align_equals
        - assign_null_coalescing_to_coalesce_equal
        - boolean_operator_linebreak_beginning
        - combine_consecutive_issets
        - combine_consecutive_unsets
        - concat_with_spaces
        - const_visibility_required
        - empty_loop_body_semicolon
        - empty_loop_condition
        - explicit_indirect_variable
        - explicit_string_variable
        - linebreak_after_opening_tag
        - method_chaining_indentation
        - multiline_comment_opening_closing
        - no_blank_lines_between_traits
        - nullable_type_declarations
        - ordered_class_elements
        - php_unit_fqcn_annotation
        - php_unit_internal_class
        - php_unit_test_case_self_method_calls
        - php_unit_test_class_requires_covers
        - phpdoc_add_missing_param_annotation
        - phpdoc_inline_inheritdoc
        - phpdoc_link_to_see
        - phpdoc_trim_consecutive_blank_line_separation
        - phpdoc_var_order
        - property_separation
        - protected_to_private
        - semicolon_after_instruction
        - simplified_if_return
        - single_space_after_construct
        - standardize_increment

    disabled:
        - unalign_equals
        - concat_without_spaces
        - not_operator_with_successor_space
        - trailing_comma_in_multiline_array
        - phpdoc_summary
        - laravel_braces
        - no_unused_imports

js: false
css: false
